### ISSUE TITLE
Should worklets get to run past the duration of the page?

### ISSUE THREAD

**Issue by pythagoraskitty** [pythagoraskitty/shared-storage#12]
This seems necessary since the caller has no idea when the worklet finishes, so how can it know when it can navigate away from the page, unless it’s confident that the worklet will continue to run after the navigation?

We’d need a timeout. How long should it be?

**Comment by jkarlin** [comment]
@xyaoinum Can you update the explainer to reflect this behavior change and then close this comment?

**Comment by xyaoinum** [comment]
Updated the explainer
