### ISSUE TITLE
Bad Actor Attacks

### ISSUE THREAD

**Issue by RussStringham** [pythagoraskitty/shared-storage#4]
There are lots of ways that this API can be abused by bad actors or by competitors. This is more general that the specific issues identified in #2.

The clear() call is very destructive, because it clears all keys for all domains; a site should not be able to clear the keys registered by all other sites. In general this should only be initiated by the user themselves when the user wants to do the equivalent of clearing all third-party cookies.  You could modify the API to require the add() and update() calls to include a domain. Clear() would also require a domain and only clear keys associated with that domain. This doesn't prevent a company from deleting its competitor's keys, but it at least makes it so that someone trying to clear their own keys doesn't unintentionally clear those of others.

Today, a domain cannot view/set/modify/delete the cookies of its competitors, because it does not have access to these third-party cookies. However, with this API, anybody can set/modify/delete any keys that they desire. For example, a company can mess with its competitors A/B tests simply by calling 
`   sharedStorage.set("competitor key", non-random-value, {ignoreIfPresent: false})`
With this they can assign everyone to the A side of the test or randomly switch them every time they visit a site running their code, invalidating their competitor's A/B testing.
This attack could be made more difficult if the set() call supported an option, `noUpdates`, which if true means that the key, once set, can never be modified. If the competitor sets the value before the owning company, they may still skew the results, but they will not be able to break any test where the user has already been assigned a value.

Another option for the A/B use case would be to only support setting the seed within the SelectURLOperation() call and require that all URLs passed to the call share the same domain. Then the seed can be tied only to that domain and only available for use in future SelectURLOperation calls for that same domain.

**Comment by jkarlin** [comment]
Sorry, I think there is a misunderstanding. Shared storage is partitioned by origin, as all storage APIs are. Reads/writes/clearing only applies to the origin of the document/context that requested it. So you can't clear or poison another origin's data.

**Comment by RussStringham** [comment]
How can you do A/B testing then? User is randomly assigned to the B group from domain X for advertiser M. User later visits domain Y. M has Y call set() again with ignoreIfPresent set to true, so its value is ignored because it already exists. User remains in B.

If Y and M don't have a relationship, what is to prevent Y calling set() with ignoreIfPresent set to false, overriding the current value? Does the code to make these calls have to have been loaded directly from M into a third-party iFrame?

**Comment by jkarlin** [comment]
If M wants to store data in its own shared storage, then it needs to do so from an M iframe.

**Comment by jkarlin** [comment]
I'm imagining a world in which you have a publisher that loads some ad-tech script, which creates a server-side bid, which returns a list of possible creatives. The ad-tech at origin A creates an iframe and sets its seed for the user with ignoreIfPresent false in case a seed has not yet been set for this user. The ad-tech then creates a shared storage worklet to determine the correct creative to display based on that seed.

If the advertiser (e.g., the one whose creative is being displayed) wants to run an a/b test. That's a different story, as it's now in a fenced frame. And we haven't yet figured out if it's safe to allow fenced frames to write or read from shared storage.
