### ISSUE TITLE
A/B test experiment and communication with Fledge worklets

### ISSUE THREAD

**Issue by BasileLeparmentier** [pythagoraskitty/shared-storage#7]
Hi,

As discussed Tuesday, It would be great to be able to have this shared storage available in the buyer or seller worklet in fledge (themselves opaque). 

Indeed, in the current set up, the ABtest can only be performed once the winner has been chosen (as you can query with only 5 urls who are therefore related to the winning campaign only) .
 It is therefore impossible to do bidding ABtest for instance (where you bid more or less , or differently on a given set of users). 

This is a very important use case for online advertising.

Many thanks,
Basile

**Comment by jkarlin** [comment]
This does sound interesting, and I've created an issue about it on the FLEDGE repo in WICG/turtledove#208. Thanks for the suggestion.
